# ~/.config/starship.toml

# Set color palette
palette = "catppuccin_mocha"

# Prompt format
add_newline = true
format = """$os$username$hostname$docker$directory$git_branch$git_status
$character"""

# Character style
[character]
success_symbol = "[❯](text)"
error_symbol = "[❯](maroon)"
vimcmd_symbol = "[❮](subtext1)"
disabled = false

# Show OS logo
[os]
format = '[$symbol](bold text) '   
disabled = true

[os.symbols]
Windows = ''
Arch = '󰣇'
Ubuntu = ''
Debian = ''

# Shows the username
[username]
style_user = "bold text"
style_root = "bold red"
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
style = "bold sky"
format = 'at [$hostname]($style) '
ssh_only = true
disabled = false

# Shows current directory
[directory]
style = "bold blue"
truncation_length = 4
read_only_style = 'red'
read_only = '  '
format = 'in [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
style = "bold green"
symbol = ''
format = 'on [$symbol $branch(:$remote_branch)]($style) '

# Shows current git status
#[git_status]
#format = '([ \( $all_status$ahead_behind\)]($style) )'
#style = 'bold green'
#conflicted = '[ confliced=${count}](red) '
#up_to_date = '[󰘽 up-to-date](green) '
#untracked = '[󰋗 untracked=${count}](red) '
#ahead = ' ahead=${count}'
#diverged = ' ahead=${ahead_count}  behind=${behind_count}'
#behind = ' behind=${count}'
#stashed = '[ stashed=${count}](green) '
#modified = '[󰛿 modified=${count}](yellow) '
#staged = '[󰐗 staged=${count}](green) '
#renamed = '[󱍸 renamed=${count}](yellow) '
#deleted = '[󰍶 deleted=${count}](red) '

# Shows docker context and namespace
[docker_context]
style = "bold sapphire"
format = "via [ $context](bold blue) "

# Disabled modules
[kubernetes]
disabled = true

[vagrant]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

# Palettes
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

